# Target position in local NED frame
float32 x
float32 y
float32 z

# Target velocity
float32 vx
float32 vy
float32 vz

# Target acceleration
float32 ax
float32 ay
float32 az

# Target yaw and rate
float32 yaw
float32 yaw_rate
---
# Whether the target position was successfully set
bool position_target_set